### ISSUE TITLE
合并broad analysis

### ISSUE THREAD

**Issue by EricYJA** [EricYJA/Flask_MusicDB#4]
@EricYJA 尽快完成
缺少dxy提供的文件

**Comment by DXYXD** [comment]
没有少文件，那个words_file是用来暂存歌词里的词，然后得到词向量，最后把词向量的模型存下来。训练词向量要花比较久的时间，所以按歌手姓名存的，words_file 就是个临时文件，可覆盖。

**Comment by EricYJA** [comment]
已完成合并。感谢@DXYDX
